### Проверка с инета https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html

In [1]:
import numpy as np

In [2]:
a_11=np.array([26.2, 103.5, 24.8, 127, 25.6, 126, 26.8, 124.8, 27.7, 124.7, 28.3, 121.6, 27.4, 149.7, 25.1, 188.8, 25.2, 193.6, 25.6, 173.9])
a_12=np.array([103.5, 26.2, 127, 24.8, 126, 25.6, 124.8, 26.8, 124.7, 27.7, 121.6, 28.3, 149.7, 27.4, 188.8, 25.1, 193.6, 25.2, 173.9, 25.6])
a_1=np.reshape(a_11, (-1, 2))
a_2=np.reshape(a_12, (-1, 2))
print(a_2)
print('*'*30)
print(a_1)
print('*'*30)
print(np.cov(a_1.T))
print('*'*30)
print(np.cov(a_2.T))
print('*'*30)
print(np.mean(a_1, axis=0))
xq=np.mean(a_1, axis=0)


[[103.5  26.2]
 [127.   24.8]
 [126.   25.6]
 [124.8  26.8]
 [124.7  27.7]
 [121.6  28.3]
 [149.7  27.4]
 [188.8  25.1]
 [193.6  25.2]
 [173.9  25.6]]
******************************
[[ 26.2 103.5]
 [ 24.8 127. ]
 [ 25.6 126. ]
 [ 26.8 124.8]
 [ 27.7 124.7]
 [ 28.3 121.6]
 [ 27.4 149.7]
 [ 25.1 188.8]
 [ 25.2 193.6]
 [ 25.6 173.9]]
******************************
[[  1.47788889 -18.04911111]
 [-18.04911111 987.30488889]]
******************************
[[987.30488889 -18.04911111]
 [-18.04911111   1.47788889]]
******************************
[ 26.27 143.36]


In [3]:
res= np.subtract(a_1, xq)
res_1=(np.dot(res[:, 0], res[:, 1]))/(len(res)-1)
print(res_1)

-18.04911111111111
